---
- hosts: tower_servers
  become: True
  vars_files:
    somevault.yml #creds for ansible tower login
  vars:
    venv_name: new_env
    venvs_parent_dir: /opt/custom_venv
    venv_packages:
      - openpyxl
  gather_facts: True
  pre_tasks:
    - name: Get current custom venv path(s)
      uri:
        url: "https://{{ ansible_default_ipv4.address }}/api/v2/settings/system/"
        method: GET
        user: "{{ toweruser }}"
        password: "{{ towerpass }}"
        force_basic_auth: yes
        return_content: True
        validate_certs: False
      register: tower_info

  roles:
    - manage_venvs
