---
python: {
  sys_version: python3.6,
  dev_version: python36-devel,
  venv_version: python3-virtualenv
}
venv_rpm_packages:
  - "{{ python.dev_version }}"
  - "{{ python.venv_version }}"
  - gcc
venvs_parent_dir: /opt/custom_venv
venv_dir: "{{ venv_name }}"
venv_name: ""
venv_requirments: requirements.txt
venv_packages: 
  - ncclient
  - netaddr
  - awxkit==17.1.0
